<?php

namespace Tests\Feature;

use http\Env\Request;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;


use App\Quiz;
use App\Http\Controllers\AdminController;
use Illuminate\Support\Collection;


class AdminContollerTest extends TestCase
{

   // use RefreshDatabase;
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub


    }

    /** @test */
    //check admin route
    public function test_check_admin_route()
    {
        $this->get('http://homestead.test/admin')->assertStatus(200);
        $this->call('GET', 'http://homestead.test/admin')->assertOk();

    }



}
